export const GET_ALL_COUNTRY = 'GET_ALL_COUNTRY';
export const GET_COUNTRY_LOADING = 'GET_COUNTRY_LOADING';
export const GET_COUNTRY_FAILED = 'GET_COUNTRY_FAILED';
export const SEARCH_COUNTRY = 'SEARCH_COUNTRY';