export const GET_COUNTRY_LOAD = 'GET_COUNTRY_LOAD';
export const GET_COUNTRY_RECEIVE = 'GET_COUNTRY_RECEIVE';
export const GET_COUNTRY_FAIL = 'GET_COUNTRY_FAIL';
export const GET_COUNTRY_DETAIL = 'GET_COUNTRY_DETAIL';